services:
  - type: web
    name: glancio-frontend
    env: node
    buildCommand: ./build.sh
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true 